title: "N'solé Samson YAMONTCHE"
name: "N'solé Samson YAMONTCHE"

description: "LaTeX Book Designer & Typesetter | Mathematics, STEM & Educational Publishing"

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "air"

plugins:
  - jekyll-include-cache

logo: "/img/samson_profil.png"

author:
  name: "N'solé Samson YAMONTCHE"
  avatar: "/img/samson_profil.png"
  bio: "LaTeX Book Designer & Typesetter specializing in Mathematics, STEM and Educational Publishing."
  location: "Benin"

locale: "en-US"

show_downloads: false
