title: "N'solé YAMONTCHE"
logo: img/samson.jpeg
description: "LaTeX Book Designer & Typesetter | Mathematics, STEM & Educational Publishing"
show_downloads: false
theme: jekyll-theme-minimal
lang: en
