title: "N'solé Samson YAMONTCHE"
name: "N'solé Samson YAMONTCHE"
description: "LaTeX Book Designer & Typesetter | Mathematics, STEM & Educational Publishing"

logo: "/img/samson_profil.png"

url: "https://nsole_samson.github.io"
baseurl: "/latex-textbook-portfolio"

repository: "nsole_samson/latex-textbook-portfolio"

minimal_mistakes_skin: "air"

locale: "en-US"

plugins:
  - jekyll-include-cache

author:
  name: "N'solé Samson YAMONTCHE"
  avatar: "/img/samson_profil.png"
  bio: "LaTeX Book Designer & Typesetter specializing in Mathematics, STEM and Educational Publishing."
  location: "Benin"
